DROP DATABASE IF EXISTS RestauranteMouro;
CREATE DATABASE RestauranteMouro;
USE RestauranteMouro;

CREATE TABLE EMPLEADOS (
    DNI VARCHAR(10) NOT NULL UNIQUE,
    Nombre VARCHAR(25) NOT NULL,
    Apellidos VARCHAR(50) NOT NULL,
    Dirección VARCHAR(50) NOT NULL,
    Ciudad VARCHAR(25) NOT NULL,
    Teléfono VARCHAR(9) NOT NULL,
    CP VARCHAR(5) NOT NULL,
    FechaAlta DATE NOT NULL,
    Categoría VARCHAR(25) NOT NULL,
    Salario DECIMAL(6,2) NOT NULL,
    PRIMARY KEY (DNI)
)ENGINE=InnoDB;

CREATE TABLE COCINEROS (
    DNI VARCHAR(10) NOT NULL UNIQUE,
    Puesto VARCHAR(25) NOT NULL,
    Especialidad VARCHAR(25) NOT NULL,
    PRIMARY KEY (DNI),
    CONSTRAINT FOREIGN KEY (DNI) REFERENCES EMPLEADOS (DNI) ON DELETE CASCADE ON UPDATE CASCADE
)ENGINE=InnoDB;

CREATE TABLE ADMINISTRACION (
    DNI VARCHAR(10) NOT NULL UNIQUE,
    Cargo VARCHAR(25) NOT NULL,
    PRIMARY KEY (DNI),
    CONSTRAINT FOREIGN KEY (DNI) REFERENCES EMPLEADOS (DNI) ON DELETE CASCADE ON UPDATE CASCADE
)ENGINE=InnoDB;

CREATE TABLE CAMAREROS (
    DNI VARCHAR(10) NOT NULL UNIQUE,
    Turno VARCHAR(25) NOT NULL,
    anhos TINYINT(2) NOT NULL,
    DNI_encargado VARCHAR(10) NOT NULL,
    PRIMARY KEY (DNI, DNI_encargado),
    CONSTRAINT FOREIGN KEY (DNI) REFERENCES EMPLEADOS (DNI) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT FOREIGN KEY (DNI_encargado) REFERENCES EMPLEADOS (DNI) ON DELETE CASCADE ON UPDATE CASCADE
)ENGINE=InnoDB;

CREATE TABLE COMEDORES (
    CodigoC VARCHAR(5) NOT NULL UNIQUE,
    Nombre VARCHAR(25) NOT NULL,
    Capacidad INT(4) NOT NULL,
    Nmesas INT(3) NOT NULL,
    Localización VARCHAR(25) NOT NULL,
    PRIMARY KEY (CodigoC)
)ENGINE=InnoDB;

CREATE TABLE MESAS (
    CodigoM VARCHAR(5) NOT NULL UNIQUE,
    CodigoC VARCHAR(5) NOT NULL UNIQUE,
    Nasientos INT(2) NOT NULL,
    DNI_camarero VARCHAR(10) NOT NULL UNIQUE,
    PRIMARY KEY (CodigoM, CodigoC),
    CONSTRAINT FOREIGN KEY (CodigoC) REFERENCES COMEDORES (CodigoC) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT FOREIGN KEY (DNI_camarero) REFERENCES EMPLEADOS (DNI) ON DELETE CASCADE ON UPDATE CASCADE
)ENGINE=InnoDB;


CREATE TABLE HACEN (
    CodigoM VARCHAR(5) NOT NULL,
    CodigoC VARCHAR(5) NOT NULL,
    Nreserva VARCHAR(8) NOT NULL UNIQUE,
    NasientosR INT(2) NOT NULL,
    PRIMARY KEY (CodigoM, CodigoC, Nreserva),
	CONSTRAINT FOREIGN KEY (CodigoM) REFERENCES MESAS (CodigoM) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT FOREIGN KEY (CodigoC) REFERENCES COMEDORES (CodigoC) ON DELETE CASCADE ON UPDATE CASCADE
)ENGINE=InnoDB;

CREATE TABLE RESERVAS (
    Nreserva VARCHAR(8) NOT NULL  UNIQUE,
    Fhreserva DATE NOT NULL, 
    Nombre VARCHAR(25) NOT NULL,
    Fhreservada DATE NOT NULL, 
    ComidaCena ENUM('comida','cena'), 
    Npersonas INT(2) NOT NULL, 
    Varios VARCHAR(128),
    PRIMARY KEY (Nreserva)
)ENGINE=InnoDB;

CREATE TABLE FACTURAS (
    NFactura INTEGER NOT NULL AUTO_INCREMENT,
    FechaF DATE NOT NULL, 
    CodigoM VARCHAR(5) NOT NULL,
    CodigoC VARCHAR(5) NOT NULL,
    PRIMARY KEY (NFactura),
    CONSTRAINT FOREIGN KEY (CodigoM) REFERENCES MESAS (CodigoM) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT FOREIGN KEY (CodigoC) REFERENCES COMEDORES (CodigoC) ON DELETE CASCADE ON UPDATE CASCADE
)ENGINE=InnoDB;

CREATE TABLE PLATOS  (
    CodigoPl VARCHAR(5) UNIQUE NOT NULL,
    Nombre VARCHAR(25) NOT NULL,
    Descripción VARCHAR(256) NOT NULL,
    Tipo VARCHAR(64) NOT NULL,
    Precio DECIMAL(6,2) NOT NULL,
    PRIMARY KEY (CodigoPl)
)ENGINE=InnoDB;

CREATE TABLE INCLUYEN (
    NFactura INTEGER NOT NULL UNIQUE,
    CodigoPl VARCHAR(5) NOT NULL,
    Unidades INT(2) NOT NULL,
	PRIMARY KEY (NFactura, CodigoPl),
    CONSTRAINT FOREIGN KEY (CodigoPl) REFERENCES PLATOS (CodigoPl) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT FOREIGN KEY (NFactura) REFERENCES FACTURAS (NFactura) ON DELETE CASCADE ON UPDATE CASCADE
)ENGINE=InnoDB;

CREATE TABLE PROVEEDORES (
    CodigoPro VARCHAR(5) UNIQUE NOT NULL,
    Dirección VARCHAR(256) NOT NULL,
    CP VARCHAR(5) NOT NULL,
    Teléfono VARCHAR(9) NOT NULL,
    Fax VARCHAR(9) NOT NULL,
    Contacto VARCHAR(128) NOT NULL,
    PRIMARY KEY (CodigoPro)
)ENGINE=InnoDB;

CREATE TABLE PRODUCTOS (
    CodigoPr VARCHAR(5) UNIQUE NOT NULL,
    Descripción VARCHAR(256) NOT NULL,
    Stock INT(3) NOT NULL,
    UnidadBase VARCHAR(5) NOT NULL,
    PrecioU DECIMAL(6,2) NOT NULL,
    Categoria VARCHAR(25) NOT NULL,
    CodigoPro VARCHAR(5) NOT NULL,
    PRIMARY KEY (CodigoPr),
    CONSTRAINT FOREIGN KEY (CodigoPro) REFERENCES PROVEEDORES (CodigoPro) ON DELETE CASCADE ON UPDATE CASCADE
)ENGINE=InnoDB;

CREATE TABLE CONTIENEN (
    CodigoPl VARCHAR(5) NOT NULL,
    CodigoPr VARCHAR(5) NOT NULL,
    Cantidad VARCHAR(5) NOT NULL,
    PRIMARY KEY (CodigoPl),
    CONSTRAINT FOREIGN KEY (CodigoPl) REFERENCES PLATOS (CodigoPl) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT FOREIGN KEY (CodigoPr) REFERENCES PRODUCTOS (CodigoPr) ON DELETE CASCADE ON UPDATE CASCADE
)ENGINE=InnoDB;
